source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'YJDLNA_Example' do
  pod 'YJDLNA', :path => '../'

  target 'YJDLNA_Tests' do
    inherit! :search_paths

    
  end
end

# 基础库中依赖的第三方库无法使用BITCODE
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        # 禁用所有 Pod 的代码签名
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_ALLOWED_FOR_SIMULATOR'] = 'NO'
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
      end
  end
end
